const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), "utf8");
const config = read("src", "features", "ai", "config.ts");
const route = read("src", "app", "api", "ai", "assistant", "route.ts");
const provider = read("src", "features", "ai", "providers", "openai-provider.ts");
const tools = read("src", "features", "ai", "tools", "registry.ts");
const redact = read("src", "features", "ai", "services", "redaction.ts");
const limiter = read("src", "features", "ai", "services", "rate-limit.ts");
assert.match(config, /OPENAI_API_KEY/);
assert.match(config, /AI_DISTRIBUTED_RATE_LIMIT_ENABLED/);
assert.match(route, /deriveAiActor/);
assert.match(route, /buildServerAiContext/);
assert.match(route, /getAiRateLimiter/);
assert.match(provider, /import "server-only"/);
assert.match(provider, /aiProviderResponseSchema\.parse/);
assert.match(provider, /redactAiOutbound/);
assert.match(tools, /search.*listing.*catalog.*video/s);
assert.doesNotMatch(tools, /seller.?contact|saved.?search|service_role|rpc\(/i);
assert.match(redact, /redacted/);
assert.match(limiter, /NODE_ENV === "production"/);
assert.doesNotMatch(route, /\.\.\.validation\.request/);
console.log("AI-01A production foundation regression passed");
