const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), "utf8");
const contract = read("src", "features", "ai", "moderation", "image-moderation.ts");
const deterministic = read("src", "features", "ai", "moderation", "image-moderation-deterministic.ts");
const runtime = read("src", "features", "ai", "moderation", "listing-image-moderation-runtime.ts");
const openai = read("src", "features", "ai", "providers", "openai-provider.ts");
for (const code of ["POSSIBLE_DUPLICATE_IMAGE", "POSSIBLE_VEHICLE_MISMATCH"]) assert.match(runtime + contract, new RegExp(code));
for (const evidence of ["[exact-duplicate-image]", "[possible-vehicle-mismatch]"]) assert.match(runtime, new RegExp(evidence.replace(/[\[\]]/g, "\\$&")));
assert.match(runtime, /createHash\("sha256"\)/);
assert.match(runtime, /canonicalDigests\.has\(digest\)/);
assert.match(runtime, /recommendedAction: "ask_edit"/);
assert.match(runtime, /recommendedAction: "review"/);
assert.match(contract, /insufficient_for_vehicle_identity/);
for (const fixture of ["motorcycle", "commercial_van", "uncertain_make", "detail"]) assert.match(deterministic + contract, new RegExp(`"${fixture}"`));
assert.match(openai, /insufficient_for_vehicle_identity/);
assert.doesNotMatch(runtime + contract, /cross-listing|cross_owner|stolen|fraud|POSSIBLE.*PRICE|signedUrl|private.*url|raw_response|provider_payload/i);
console.log("AI-01G-C2B exact duplicate and vehicle mismatch contract passed");
