const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), "utf8");
const intent = read("src", "features", "ai", "search", "search-intent.ts");
const service = read("src", "features", "ai", "search", "search-service.ts");
const validator = read("src", "features", "ai", "services", "request-validator.ts");
const route = read("src", "app", "api", "ai", "assistant", "route.ts");

assert.match(intent, /searchIntentSchema/);
assert.match(intent, /\.strict\(\)/);
assert.match(intent, /mergeSearchIntent/);
assert.match(intent, /operation: z\.enum\(\["set", "clear", "keep", "reset"\]\)/);
assert.match(intent, /mapSearchIntentToSearchV1/);
assert.match(intent, /has_video/);
assert.match(intent, /verifiedDealer[\s\S]*unsupported: true/);
assert.match(intent, /milyon|million/);
assert.match(intent, /mileageMax/);
assert.match(intent, /The model does not belong to the selected make/);
assert.match(intent, /The district does not belong to the selected city/);
assert.match(service, /schema\("marketplace"\)\.rpc\("search_listings_v1"/);
assert.doesNotMatch(service, /seller_contact|service_role|from\("listings"\)/);
assert.match(service, /publicItem/);
assert.doesNotMatch(service, /cover_image_url/);
assert.match(validator, /searchIntentSchema\.safeParse/);
assert.match(route, /deriveAiActor/);
assert.match(route, /getAiRateLimiter/);
console.log("AI-01B natural-language Search v1 adapter contract passed");
