const assert = require("node:assert/strict");
const { execFileSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..", "..", "..");
const migration = fs.readFileSync(path.join(root, "supabase", "migrations", "20260913100000_functional_02c2_search_request.sql"), "utf8");
const source = fs.readFileSync(path.join(root, "supabase", "migrations", "20260912153003_functional_02c1b1_listing_search_projection_schema.sql"), "utf8");
assert.match(migration, /CREATE FUNCTION marketplace\.search_listings_v1\(p_request JSONB\)/);
assert.match(migration, /FROM marketplace\.listing_search_documents AS d/);
assert.match(source, /CREATE TABLE marketplace\.listing_search_documents/);
for (const filter of ["make_ids", "model_ids", "variant_ids", "city_ids", "district_ids", "price_min", "price_max", "year_min", "year_max", "mileage_min", "mileage_max", "fuel_types", "transmissions", "body_types", "drive_types", "colors", "seller_types", "engine_volume_min", "power_kw_min", "battery_capacity_kwh_min", "electric_range_km_min", "seller_service_declarations", "seller_damage_declarations", "trade_in_accepted", "price_negotiable", "has_photos", "has_video"]) assert.match(migration, new RegExp(`'${filter}'`));
for (const sort of ["newest", "price_asc", "price_desc", "year_desc", "mileage_asc"]) assert.match(migration, new RegExp(`'${sort}'`));
for (const token of ["ILIKE", "ESCAPE E'\\\\'", "LIMIT v_limit", "d.listing_id ASC", "jsonb_build_object('version', 'v1'"]) assert.ok(migration.includes(token), token);

const db = ["exec", "supabase_db_Otoyali-blueprint", "psql", "-q", "-U", "postgres", "-d", "postgres", "-Atc"];
const query = (sql) => execFileSync("docker", [...db, sql], { encoding: "utf8" }).trim();
const invoke = (request) => JSON.parse(query(`SELECT marketplace.search_listings_v1('${JSON.stringify(request).replaceAll("'", "''")}'::jsonb);`));
const response = invoke({ version: "v1", limit: 1, sort: "newest", filters: {} });
assert.deepEqual(Object.keys(response).sort(), ["items", "next_cursor", "version"]);
assert.equal(response.version, "v1"); assert.ok(Array.isArray(response.items)); assert.ok(response.items.length <= 1);
for (const item of response.items) assert.deepEqual(Object.keys(item).sort(), ["battery_capacity_kwh","body_type","city_id","city_name","color","condition","cover_image_url","currency","district_id","district_name","drive_type","electric_range_km","engine_volume_l","fuel_type","has_video","listing_id","make_id","make_name","mileage_km","model_id","model_name","photo_count","power_kw","price_amount","price_negotiable","projected_at","published_at","seller_damage_declaration","seller_service_declaration","seller_type","trade_in_accepted","transmission","variant_id","variant_name","year"].sort());
for (const invalid of [{ version: "v2" }, { version: "v1", filters: { unknown: true } }, { version: "v1", limit: 61 }, { version: "v1", sort: "unknown" }]) assert.throws(() => invoke(invalid));
const { randomUUID } = require("node:crypto");
const ids = Object.fromEntries(["seller", "make", "model", "vehicle"].map((key) => [key, randomUUID()]));
const listingIds = Array.from({ length: 65 }, () => randomUUID());
const fixtures = listingIds.map((id, index) => `('${id}', '${ids.vehicle}', '${ids.seller}', 'active', 'active', 'Characterization ${index}', 100000, 'TRY', false, 'Istanbul', 'private')`).join(",");
const pages = query(`BEGIN;
INSERT INTO auth.users(instance_id,id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) VALUES ('00000000-0000-0000-0000-000000000000','${ids.seller}','authenticated','authenticated','b0a1-${ids.seller}@test.invalid','{}','{}',now(),now());
INSERT INTO vehicle.makes(id,name,slug) VALUES ('${ids.make}','B0 A1 Make','b0-a1-${ids.make}');
INSERT INTO vehicle.models(id,make_id,name,slug) VALUES ('${ids.model}','${ids.make}','B0 A1 Model','b0-a1-${ids.model}');
INSERT INTO vehicle.vehicle_profiles(id,make_id,model_id,year,mileage_km,fuel_type,transmission,created_source,profile_status,created_by) VALUES ('${ids.vehicle}','${ids.make}','${ids.model}',2024,100,'gasoline','automatic','manual','active','${ids.seller}');
INSERT INTO vehicle.profile_ownership(vehicle_profile_id,owner_id,ownership_type,is_current) VALUES ('${ids.vehicle}','${ids.seller}','owner',true);
INSERT INTO marketplace.listings(id,vehicle_profile_id,seller_id,status,moderation_status,title,price_amount,currency,price_negotiable,city,seller_type) VALUES ${fixtures};
WITH first_page AS (SELECT marketplace.search_listings_v1('{"version":"v1","limit":60,"sort":"price_asc","filters":{"q":"B0 A1"}}'::jsonb) AS body), second_page AS (SELECT marketplace.search_listings_v1(jsonb_set('{"version":"v1","limit":60,"sort":"price_asc","filters":{"q":"B0 A1"}}'::jsonb, '{cursor}', first_page.body->'next_cursor')) AS body FROM first_page) SELECT jsonb_build_object('first', first_page.body, 'second', second_page.body) FROM first_page, second_page;
ROLLBACK;`).split(/\r?\n/).filter((line) => line.startsWith("{"));
const { first: firstPage, second: secondPage } = JSON.parse(pages[0]);
assert.equal(firstPage.items.length, 60, "public Search v1 remains capped at 60");
assert.ok(firstPage.next_cursor, "a full first page has a cursor");
assert.equal(new Set(firstPage.items.map((item) => item.listing_id)).size, 60, "page contains no duplicate listings");
assert.equal(secondPage.items.length, 5, "cursor returns the remaining fixture rows");
assert.ok(secondPage.next_cursor, "current contract returns a cursor for every non-empty page, including the terminal page");
const firstIds = firstPage.items.map((item) => item.listing_id);
const secondIds = secondPage.items.map((item) => item.listing_id);
assert.deepEqual(Object.keys(firstPage.next_cursor).sort(), ["listing_id", "mileage_km", "price_amount", "published_at", "sort", "version", "year"]);
assert.equal(firstPage.next_cursor.version, "v1"); assert.equal(firstPage.next_cursor.sort, "price_asc");
assert.equal(new Set(secondIds).size, 5, "second page contains no duplicates");
assert.equal(secondIds.filter((id) => firstIds.includes(id)).length, 0, "pages do not overlap");
const union = new Set([...firstIds, ...secondIds]);
assert.equal(union.size, 65, "cursor union contains all fixtures exactly once");
assert.deepEqual([...union].sort(), [...listingIds].sort(), "cursor traversal has no missing or unexpected fixture rows");
assert.ok(firstIds[59] < secondIds[0], "listing_id tie-break continues deterministically for equal prices");
console.log("FUNCTIONAL-03B-B0-A1 Search v1 characterization contract passed");
