const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process'),{randomUUID,createHmac}=require('node:crypto'),{createClient}=require('@supabase/supabase-js');
const root=path.resolve(__dirname,'..','..','..'),web=path.join(root,'apps','web'),read=(...p)=>fs.readFileSync(path.join(web,...p),'utf8');
const migration=fs.readFileSync(path.join(root,'supabase','migrations','20261001190811_sell_sec_04b1_finalize_seller_phone_verification.sql'),'utf8'),start=read('src','app','api','seller','phone-verification','start','route.ts'),verify=read('src','app','api','seller','phone-verification','verify','route.ts'),runtime=read('src','lib','seller-phone-verification','runtime.ts'),provider=read('src','lib','seller-phone-verification','provider.ts');
assert.match(migration,/FOR UPDATE/);assert.match(migration,/INSERT INTO identity\.seller_phone_verifications/);assert.match(migration,/UPDATE identity\.seller_phone_verification_challenges/);assert.match(migration,/finalize_seller_phone_verification_service/);assert.match(migration,/REVOKE ALL[\s\S]*PUBLIC, anon, authenticated, service_role/);assert.match(start,/requireAuthenticatedRequestSupabase/);assert.match(verify,/requireAuthenticatedRequestSupabase/);assert.match(runtime,/normalizeTurkeySellerPhone/);assert.match(runtime,/reserve_seller_phone_verification_challenge_service/);assert.match(runtime,/get_seller_phone_verification_challenge_service/);assert.match(runtime,/finalize_seller_phone_verification_service/);assert.doesNotMatch(runtime+start+verify,/auth\.(signInWithOtp|verifyOtp|updateUser|admin)/);assert.match(provider,/createDeterministicSellerPhoneVerificationProvider/);
const db=['exec','supabase_db_Otoyali-blueprint','psql','-q','-U','postgres','-d','postgres','-v','ON_ERROR_STOP=1','-Atc'],q=s=>execFileSync('docker',[...db,s],{encoding:'utf8'}).trim().split(/\r?\n/).filter(Boolean),secret=execFileSync('docker',['inspect','-f','{{range .Config.Env}}{{println .}}{{end}}','supabase_auth_Otoyali-blueprint'],{encoding:'utf8'}).split(/\r?\n/).find(x=>x.startsWith('GOTRUE_JWT_SECRET='))?.slice(18);assert.ok(secret);const enc=v=>Buffer.from(JSON.stringify(v)).toString('base64url'),token=(role,sub)=>{const h=enc({alg:'HS256',typ:'JWT'}),b=enc({role,aud:'authenticated',exp:Math.floor(Date.now()/1000)+300,...(sub?{sub}:{})});return `${h}.${b}.${createHmac('sha256',secret).update(`${h}.${b}`).digest('base64url')}`};
(async()=>{
  const user=randomUUID(),other=randomUUID(),third=randomUUID(),url='http://127.0.0.1:54321';
  q(`INSERT INTO auth.users(instance_id,id,aud,role,phone,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)VALUES('00000000-0000-0000-0000-000000000000','${user}','authenticated','authenticated','+77011234567','{}','{}',now(),now()),('00000000-0000-0000-0000-000000000000','${other}','authenticated','authenticated','+905551111111','{}','{}',now(),now()),('00000000-0000-0000-0000-000000000000','${third}','authenticated','authenticated','+905552222222','{}','{}',now(),now());`);
  try {
    const service=createClient(url,token('service_role'),{auth:{persistSession:false}}),anon=createClient(url,token('anon'),{auth:{persistSession:false}}),auth=createClient(url,token('authenticated',user),{auth:{persistSession:false}});
    assert.equal(q(`SELECT public.is_turkey_seller_phone_verified() FROM auth.users WHERE id='${user}'`).join(''),'f');
    const reserve=async(phone)=>{let r=await service.rpc('reserve_seller_phone_verification_challenge_service',{p_user_id:user,p_phone_e164:phone});assert.ifError(r.error);let c=Array.isArray(r.data)?r.data[0]:r.data;assert.equal(c.outcome,'reserved');let m=await service.rpc('mark_seller_phone_verification_challenge_sent_service',{p_challenge_id:c.challenge_id,p_provider_reference:'VE00000000000000000000000000000000'});assert.ifError(m.error);assert.equal(m.data,true);return c.challenge_id};
    let first=await reserve('+905551234567'); let foreign=await service.rpc('finalize_seller_phone_verification_service',{p_user_id:other,p_challenge_id:first});assert.ifError(foreign.error);assert.deepEqual(foreign.data,[]);
    let done=await service.rpc('finalize_seller_phone_verification_service',{p_user_id:user,p_challenge_id:first});assert.ifError(done.error);assert.equal((Array.isArray(done.data)?done.data[0]:done.data).phone_e164,'+905551234567');assert.equal(q(`SELECT v.phone_e164||'|'||c.status FROM identity.seller_phone_verifications v JOIN identity.seller_phone_verification_challenges c ON c.user_id=v.user_id WHERE v.user_id='${user}' ORDER BY c.created_at DESC LIMIT 1`)[0],'+905551234567|consumed');
    let replay=await service.rpc('finalize_seller_phone_verification_service',{p_user_id:user,p_challenge_id:first});assert.ifError(replay.error);assert.deepEqual(replay.data,[]);
    q(`UPDATE identity.seller_phone_verification_challenges SET created_at=created_at-interval '61 seconds' WHERE id='${first}'`);
    let replacement=await reserve('+905551234568');let second=await service.rpc('finalize_seller_phone_verification_service',{p_user_id:user,p_challenge_id:replacement});assert.ifError(second.error);assert.equal(q(`SELECT phone_e164 FROM identity.seller_phone_verifications WHERE user_id='${user}'`)[0],'+905551234568');assert.equal(q(`SELECT count(*) FROM identity.seller_phone_verifications WHERE phone_e164='+905551234567'`)[0],'0');
    const direct=q(`BEGIN;CREATE TEMP TABLE r(n text primary key,ok bool);GRANT SELECT,INSERT ON r TO anon,authenticated;SET LOCAL ROLE authenticated;DO $$BEGIN BEGIN INSERT INTO identity.seller_phone_verifications(user_id,phone_e164)VALUES('${other}','+905551234567');INSERT INTO r VALUES('direct DML denied',false);EXCEPTION WHEN insufficient_privilege THEN INSERT INTO r VALUES('direct DML denied',true);END;END$$;RESET ROLE;SELECT n||'|'||ok FROM r;ROLLBACK;`);assert.ok(direct.includes('direct DML denied|true'));
    let deniedAnon=await anon.rpc('finalize_seller_phone_verification_service',{p_user_id:user,p_challenge_id:replacement}),deniedAuth=await auth.rpc('finalize_seller_phone_verification_service',{p_user_id:user,p_challenge_id:replacement});assert.ok(deniedAnon.error&&deniedAuth.error);console.log('PASS SELL-SEC-04B1 authenticated service-finalizer, ownership, replacement, replay, privileges, and Auth-phone independence');
  } finally { q(`DELETE FROM auth.users WHERE id IN ('${user}','${other}','${third}');`); }
})().catch(e=>{console.error(e.stack||e.message);process.exitCode=1});
