"use client";

import { FormEvent, KeyboardEvent, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/Button";
import { Textarea } from "@/components/ui/Input";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import type { Locale } from "@/i18n/types";

type Draft = Record<string, string | number | boolean | null | undefined>;
type AssistantState = { draft: Draft; listingId?: string; phase: "editing" | "review_ready" | "awaiting_confirmation" | "saved" | "description_preview"; pendingAction: "create" | "update" | "submit" | null; missingFields: string[]; nextQuestion?: string; clarification?: { message: string }; readyForReview: boolean; descriptionPreview?: string };
const initialDraft: Draft = { variantId: null, cityId: null, districtId: null, bodyType: null, driveType: null, color: null, engineVolumeL: null, damageState: null, ownerCount: null, description: null };

const copy = {
  tr: { title: "AI ile hızlı ilan oluştur", help: "Araç bilgilerinizi doğal dilde yazın; taslak yalnızca siz onayladığınızda kaydedilir.", open: "Asistanı aç", close: "Asistanı kapat", label: "Araç bilgilerinizi yazın", placeholder: "Örnek: 2021 BMW 520i, 75 bin kilometre, otomatik", send: "Gönder", sending: "İşleniyor", reset: "Oturumu sıfırla", summary: "Canlı taslak", missing: "Eksik", review: "Taslak incelemeye hazır", create: "İlan taslağını oluştur", update: "Değişiklikleri kaydet", submit: "İlanı incelemeye gönder", describe: "Açıklama oluştur", apply: "Uygula", regenerate: "Yeniden oluştur", discard: "Vazgeç", retry: "Tekrar dene", concise: "Kısa", standard: "Standart", detailed: "Detaylı", error: "Asistan şu anda isteği işleyemiyor. Lütfen tekrar deneyin." },
  en: { title: "Create a listing faster with AI", help: "Describe your vehicle naturally; a draft is saved only after your confirmation.", open: "Open assistant", close: "Close assistant", label: "Describe your vehicle", placeholder: "Example: 2021 BMW 520i, 75 thousand km, automatic", send: "Send", sending: "Working", reset: "Reset session", summary: "Live draft", missing: "Missing", review: "Draft is ready for review", create: "Create listing draft", update: "Save changes", submit: "Send listing for review", describe: "Generate description", apply: "Apply", regenerate: "Regenerate", discard: "Discard", retry: "Retry", concise: "Concise", standard: "Standard", detailed: "Detailed", error: "The assistant cannot process this request right now. Please try again." }
} as const;

export function SellAssistant({ locale, editListingId }: { locale: Locale; editListingId: string | null }) {
  const t = copy[locale]; const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [state, setState] = useState<AssistantState | null>(null); const [mode, setMode] = useState<"concise" | "standard" | "detailed">("standard"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const lastAction = useRef<"turn" | "generate_description">("turn");
  const draft = state?.draft ?? initialDraft; const fields = useMemo(() => [["makeId", locale === "tr" ? "Marka" : "Make"], ["modelId", locale === "tr" ? "Model" : "Model"], ["year", locale === "tr" ? "Yıl" : "Year"], ["mileageKm", locale === "tr" ? "Kilometre" : "Mileage"], ["fuelType", locale === "tr" ? "Yakıt" : "Fuel"], ["transmission", locale === "tr" ? "Vites" : "Transmission"], ["priceAmount", locale === "tr" ? "Fiyat" : "Price"], ["city", locale === "tr" ? "Şehir" : "City"]] as const, [locale]);
  async function request(action: "turn" | "confirm_create" | "confirm_update" | "confirm_submit" | "generate_description" | "regenerate_description" | "discard_description" | "apply_description", text = message) {
    if (busy) return; if (action === "turn" && !text.trim()) return setError(t.error);
    setBusy(true); setError(null); lastAction.current = action === "generate_description" || action === "regenerate_description" ? "generate_description" : "turn";
    try { const session = (await getSupabaseBrowserClient().auth.getSession()).data.session; if (!session) throw new Error("auth_required");
      const response = await fetch("/api/ai/sell", { method: "POST", headers: { Authorization: `Bearer ${session.access_token}`, "Content-Type": "application/json" }, body: JSON.stringify({ locale, message: text || undefined, draft, listingId: state?.listingId ?? editListingId ?? undefined, action, descriptionMode: mode, descriptionPreview: state?.descriptionPreview }) });
      const body = await response.json(); if (!response.ok || !body.data?.state) throw new Error(body.error?.code ?? "failure"); setState(body.data.state); if (action === "turn") setMessage("");
    } catch { setError(t.error); } finally { setBusy(false); }
  }
  function submit(event: FormEvent) { event.preventDefault(); void request("turn"); }
  function keyDown(event: KeyboardEvent<HTMLTextAreaElement>) { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void request("turn"); } }
  if (!open) return <section className="mb-5 rounded-oto border border-oto-border bg-white p-4 shadow-soft"><h2 className="font-black text-oto-text">{t.title}</h2><p className="mt-1 text-sm text-oto-muted">{t.help}</p><Button className="mt-3" type="button" variant="secondary" onClick={() => setOpen(true)}>{t.open}</Button></section>;
  return <section className="mb-5 rounded-oto border border-oto-blue/30 bg-white p-4 shadow-soft" aria-labelledby="sell-assistant-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="sell-assistant-title" className="font-black text-oto-text">{t.title}</h2><p className="text-sm text-oto-muted">{t.help}</p></div><Button type="button" variant="secondary" onClick={() => setOpen(false)} disabled={busy}>{t.close}</Button></div>
    <form className="mt-4" onSubmit={submit}><label htmlFor="sell-assistant-message" className="font-bold text-sm text-oto-text">{t.label}</label><Textarea id="sell-assistant-message" value={message} maxLength={2000} rows={3} placeholder={t.placeholder} onChange={(event) => setMessage(event.target.value)} onKeyDown={keyDown} disabled={busy} aria-describedby="sell-assistant-status" /><div className="mt-2 flex flex-wrap gap-2"><Button type="submit" disabled={busy || !message.trim()}>{busy ? t.sending : t.send}</Button><Button type="button" variant="secondary" disabled={busy} onClick={() => { setState(null); setMessage(""); setError(null); }}>{t.reset}</Button>{error ? <Button type="button" variant="secondary" disabled={busy} onClick={() => void request(lastAction.current)}>{t.retry}</Button> : null}</div></form>
    <div id="sell-assistant-status" className="mt-3" aria-live="polite" aria-atomic="true">{busy ? <p className="text-sm text-oto-muted">{t.sending}</p> : null}{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}{state?.clarification ? <p className="text-sm font-bold text-oto-text">{state.clarification.message}</p> : null}{state?.nextQuestion ? <p className="text-sm font-bold text-oto-text">{state.nextQuestion}</p> : null}</div>
    <div className="mt-4 grid gap-3 md:grid-cols-2"><section className="rounded-md border border-oto-border p-3" aria-label={t.summary}><h3 className="font-bold text-oto-text">{t.summary}</h3><dl className="mt-2 space-y-1 text-sm">{fields.map(([key, label]) => <div key={key} className="flex justify-between gap-3"><dt className="text-oto-muted">{label}</dt><dd className={draft[key] === undefined || draft[key] === null || draft[key] === "" ? "font-bold text-amber-700" : "font-bold text-oto-text"}>{draft[key] === undefined || draft[key] === null || draft[key] === "" ? t.missing : String(draft[key])}</dd></div>)}</dl></section>
      <section className="rounded-md border border-oto-border p-3"><div className="flex items-center justify-between gap-2"><h3 className="font-bold text-oto-text">{locale === "tr" ? "Açıklama" : "Description"}</h3><select aria-label={locale === "tr" ? "Açıklama uzunluğu" : "Description length"} className="rounded border border-oto-border p-1 text-sm" value={mode} onChange={(event) => setMode(event.target.value as typeof mode)} disabled={busy}><option value="concise">{t.concise}</option><option value="standard">{t.standard}</option><option value="detailed">{t.detailed}</option></select></div><Button className="mt-2" type="button" variant="secondary" disabled={busy || !state?.readyForReview} onClick={() => void request("generate_description")}>{t.describe}</Button>{state?.descriptionPreview ? <div className="mt-3 rounded bg-oto-surface p-2 text-sm"><p>{state.descriptionPreview}</p><div className="mt-2 flex flex-wrap gap-2"><Button type="button" disabled={busy} onClick={() => void request("apply_description")}>{t.apply}</Button><Button type="button" variant="secondary" disabled={busy} onClick={() => void request("regenerate_description")}>{t.regenerate}</Button><Button type="button" variant="secondary" disabled={busy} onClick={() => void request("discard_description")}>{t.discard}</Button></div></div> : null}</section></div>
    {state?.readyForReview ? <section className="mt-4 rounded-md border border-oto-blue/30 bg-oto-surface p-3"><h3 className="font-black text-oto-text">{t.review}</h3><div className="mt-3 flex flex-wrap gap-2">{state.listingId || editListingId ? <Button type="button" disabled={busy} onClick={() => void request("confirm_update")}>{t.update}</Button> : <Button type="button" disabled={busy} onClick={() => void request("confirm_create")}>{t.create}</Button>}{state.phase === "saved" && state.listingId ? <Button type="button" variant="secondary" disabled={busy} onClick={() => void request("confirm_submit")}>{t.submit}</Button> : null}</div></section> : null}
  </section>;
}
