"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getSupabaseBrowserClient, hasSupabaseEnv } from "@/lib/supabase/client";
import { Button } from "@/components/ui/Button";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/States";
import { localizePath } from "@/i18n/config";
import { useI18n } from "@/i18n/client";
type Row={conversationId:string;lastMessageAt:string|null;unreadCount:number};
export function InboxClient(){const {locale,dictionary}=useI18n();const [rows,setRows]=useState<Row[]|null>(null);const [error,setError]=useState(false);const load=async()=>{setError(false);if(!hasSupabaseEnv())return setError(true);const {data}=await getSupabaseBrowserClient().auth.getSession();if(!data.session)return setError(true);try{const r=await fetch("/api/conversations?limit=20",{cache:"no-store",headers:{Authorization:`Bearer ${data.session.access_token}`}});const j=await r.json() as {data?:Row[]};if(!r.ok||!Array.isArray(j.data))throw new Error();setRows(j.data)}catch{setError(true)}};useEffect(()=>{void load()},[]);if(rows===null&&!error)return <LoadingState label={String(dictionary.messages.loading)}/>;if(error)return <div className="grid gap-3"><ErrorState message={String(dictionary.messages.unavailable)}/><Button onClick={()=>void load()}>{String(dictionary.messages.retry)}</Button></div>;if(!rows?.length)return <EmptyState title={String(dictionary.messages.emptyTitle)} body={String(dictionary.messages.emptyBody)} tone="profile"/>;return <section className="mx-auto max-w-3xl"><h1 className="text-2xl font-black text-oto-text">{String(dictionary.messages.title)}</h1><div className="mt-5 grid gap-3">{rows.map(row=><Link key={row.conversationId} href={localizePath(`/profile/messages/${row.conversationId}`,locale)} className="rounded-oto border border-oto-border bg-white p-4 shadow-soft hover:border-oto-blue"><div className="flex items-center justify-between gap-3"><p className="font-black text-oto-text">{String(dictionary.messages.conversation)}</p>{row.unreadCount>0?<span className="rounded-full bg-oto-blue px-2 py-1 text-xs font-bold text-white" aria-label={String(dictionary.messages.unread)}>{row.unreadCount}</span>:null}</div><p className="mt-1 text-sm text-oto-muted">{row.lastMessageAt?new Intl.DateTimeFormat(locale==="en"?"en-US":"tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(row.lastMessageAt)):String(dictionary.common.noInfo)}</p></Link>)}</div></section>}
